/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsShrinkOptions {
  contextLines?: number
  maxSymbols?: number
  format?: string
  includeImports?: boolean
}

export interface JsShrinkResult {
  compressed: string
  stats: JsShrinkStats
}

export interface JsShrinkStats {
  filesScanned: number
  filesMatched: number
  symbolsFound: number
  symbolsReturned: number
  inputLines: number
  outputLines: number
  compressionRatio: number
}

export declare function shrink(query: string, path: string, options?: JsShrinkOptions | undefined | null): JsShrinkResult
